### ISSUE TITLE
Undefined variable 'utils' in html_decapsulator.py

### ISSUE THREAD

**Issue by doerrf** [fleetingbytes/rtfparse#42]
```Traceback (most recent call last):
  File "C:\Users\User\Documents\parser.py", line 14, in <module>
    renderer.render(parsed, f)
  File "C:\Users\User\Documents\venv\Lib\site-packages\rtfparse\renderers\html_decapsulator.py", line 98, in render
    self.render(item, file)
  File "C:\Users\User\Documents\venv\Lib\site-packages\rtfparse\renderers\html_decapsulator.py", line 105, in render
    self.render_symbol(item, file)
  File "C:\Users\User\Documents\venv\Lib\site-packages\rtfparse\renderers\html_decapsulator.py", line 88, in render_symbol
    utils.warn(f"Found an IGNORABLE control symbol which is not a group start!")
    ^^^^^
NameError: name 'utils' is not defined
```

I'm not sure what "utils" is meant to be, but I resolved  this issue by adding the following to html_decapsulator.py:
```
class utils:
    @staticmethod
    def warn(message: str) -> str:
        return f"WARNING: {message}"
    
    @staticmethod
    def error(message: str) -> str:
        return f"ERROR: {message}"
```

**Comment by fleetingbytes** [comment]
Thanks for this issue. Error is caused by a missing import. `utils` refer to [this module](https://github.com/fleetingbytes/rtfparse/blob/master/src/rtfparse/utils.py). The function warn was just prepending a symbol before the message line, similar to your `f"WARNING: {message}"`. I will fix this. I am just considering whether to drop this extra warning decoration alltogether.

**Comment by fleetingbytes** [comment]
@doerrf This is now fixed in the current rtfparse version. I wonder how you came about this error. If you don't mind, please share the rtf producing the error. I suspect that there is a deeper problem in rtfparse than just this missing import had been. To me it looks like rtfparse may be ignoring certain control words which it isn't supposed to ignore.

**Comment by doerrf** [comment]
Sure. I'll have to remove some proprietary elements from the RTF, since
it's proprietary data, but when I get some time I'll try to isolate the
specific lines of text that are causing the error.
